#!/bin/sh

[ "$(uci -q get dae.config.enabled)" = "1" ] && exit 0

touch /etc/config/dae
uci set dae.config.enabled='0'
uci set dae.config.config_file='/etc/dae/config.dae'
uci set dae.config.geodb='loyalsoldier'
uci commit

return 0
